# Generated by Django 4.2.16 on 2026-06-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_ven'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Req',
        ),
        migrations.DeleteModel(
            name='Ven',
        ),
    ]
